name: 'SendGrid Mail Action'
description: 'Send emails using SendGrid on actions'
branding:
    icon: 'message-square'
    color: 'green'
inputs:
    sendgrid-token:
        description: 'The token for sendgrid'
        required: true
    mail:
        description: 'The emails ( can be only one ) that the email will go'
        required: true
    from:
        description: 'The email that will be shown as sender'
        required: false
        default: 'sendgridmailaction@github.com'
    subject:
        description: 'The subject of the email'
        required: false
        default: 'GitHub action notification'
    individual:
        description: 'Defines if it should be one email with multiple address or multiple emails with a single address'
        required: falase
        default: false
    text:
        description: 'The body of the mail. The placeholders that can be used are $EVENT$, $ISSUE$, $ACTION$'
        required: false
        default: The following action $ACTION$ produced an event $EVENT$ 
    splitterator:
        description: 'The splitterator that was used for the emails'
        required: false
        default: ','
runs:
    using: 'node16'
    main: 'dist/index.js'
